module.exports = {
  AnalysisOutputService: require('./analysis/AnalysisOutputService'),
  ArchitectureService: require('./analysis/ArchitectureService'),
  AuthService: require('./security/AuthService'),
  CodeQualityService: require('./analysis/CodeQualityService'),
  CursorIDEService: require('./ide/CursorIDEService'),
  FileSystemService: require('./shared/FileSystemService'),
  IDEMirrorService: require('./ide/IDEMirrorService'),
  IDEWorkspaceDetectionService: require('./ide/IDEWorkspaceDetectionService'),
  PerformanceService: require('./analysis/PerformanceService'),
  ProjectMappingService: require('./shared/ProjectMappingService'),
  ScriptGenerationService: require('./ScriptGenerationService'),
  SecurityService: require('./security/SecurityService'),
  TaskAnalysisService: require('./task/TaskAnalysisService'),
  
  TaskGenerationService: require('./task/TaskGenerationService'),
  TaskMonitoringService: require('./task/TaskMonitoringService'),
  TaskOptimizationService: require('./task/TaskOptimizationService'),
  TaskSchedulingService: require('./task/TaskSchedulingService'),
  TaskSecurityService: require('./task/TaskSecurityService'),
  TaskService: require('./task/TaskService'),
  
  TaskValidationService: require('./task/TaskValidationService'),
  SubprojectDetector: require('./analysis/SubprojectDetector'),
}; 