module.exports = {
  AnalysisOutputService: require('./AnalysisOutputService'),
  ArchitectureService: require('./ArchitectureService'),
  AuthService: require('./AuthService'),
  CodeQualityService: require('./CodeQualityService'),
  CursorIDEService: require('./CursorIDEService'),
  FileSystemService: require('./FileSystemService'),
  IDEMirrorService: require('./IDEMirrorService'),
  IDEWorkspaceDetectionService: require('./IDEWorkspaceDetectionService'),
  PerformanceService: require('./PerformanceService'),
  ProjectMappingService: require('./ProjectMappingService'),
  ScriptGenerationService: require('./ScriptGenerationService'),
  SecurityService: require('./SecurityService'),
  TaskAnalysisService: require('./TaskAnalysisService'),
  TaskExecutionService: require('./TaskExecutionService'),
  TaskGenerationService: require('./TaskGenerationService'),
  TaskMonitoringService: require('./TaskMonitoringService'),
  TaskOptimizationService: require('./TaskOptimizationService'),
  TaskSchedulingService: require('./TaskSchedulingService'),
  TaskSecurityService: require('./TaskSecurityService'),
  TaskService: require('./TaskService'),
  TaskSuggestionService: require('./TaskSuggestionService'),
  TaskValidationService: require('./TaskValidationService'),
}; 