-- Migration: Add subcategory column to tasks table
-- Date: 2024-12-19
-- Description: Adds subcategory column to support hierarchical task categories

-- Add subcategory column
ALTER TABLE tasks ADD COLUMN subcategory TEXT;

-- Create index for better performance on category queries
CREATE INDEX IF NOT EXISTS idx_tasks_category_subcategory ON tasks(category, subcategory);

-- Update existing tasks to have proper category/subcategory mapping
UPDATE tasks SET
  category = CASE
    WHEN type LIKE 'refactor_%' THEN 'refactoring'
    WHEN type LIKE 'test_%' THEN 'testing'
    WHEN type LIKE 'deploy_%' THEN 'deployment'
    WHEN type LIKE 'security_%' THEN 'security'
    WHEN type LIKE 'analysis_%' THEN 'analysis'
    WHEN type LIKE 'optimization_%' THEN 'optimization'
    WHEN type LIKE 'documentation_%' THEN 'documentation'
    WHEN type LIKE 'generate_%' THEN 'generate'
    WHEN type LIKE 'management_%' THEN 'management'
    WHEN type LIKE 'validation_%' THEN 'validation'
    ELSE 'manual'
  END,
  subcategory = CASE
    WHEN type = 'refactor_node' THEN 'node'
    WHEN type = 'refactor_react' THEN 'react'
    WHEN type = 'refactor_frontend' THEN 'frontend'
    WHEN type = 'refactor_backend' THEN 'backend'
    WHEN type = 'refactor_database' THEN 'database'
    WHEN type = 'refactor_api' THEN 'api'
    WHEN type = 'test_unit' THEN 'unit'
    WHEN type = 'test_integration' THEN 'integration'
    WHEN type = 'test_e2e' THEN 'e2e'
    WHEN type = 'test_performance' THEN 'performance'
    WHEN type = 'test_security' THEN 'security'
    WHEN type = 'test_coverage' THEN 'coverage'
    WHEN type = 'test_fix' THEN 'fix'
    WHEN type = 'test_refactor' THEN 'refactor'
    WHEN type = 'test_status' THEN 'status'
    WHEN type = 'test_report' THEN 'report'
    WHEN type = 'deploy_production' THEN 'production'
    WHEN type = 'deploy_staging' THEN 'staging'
    WHEN type = 'deploy_docker' THEN 'docker'
    WHEN type = 'deploy_kubernetes' THEN 'kubernetes'
    WHEN type = 'deploy_infrastructure' THEN 'infrastructure'
    WHEN type = 'deploy_monitoring' THEN 'monitoring'
    WHEN type = 'deploy_rollback' THEN 'rollback'
    WHEN type = 'deploy_ci_cd' THEN 'ci_cd'
    WHEN type = 'security_audit' THEN 'audit'
    WHEN type = 'security_vulnerabilities' THEN 'vulnerabilities'
    WHEN type = 'security_authentication' THEN 'authentication'
    WHEN type = 'security_authorization' THEN 'authorization'
    WHEN type = 'security_encryption' THEN 'encryption'
    WHEN type = 'security_compliance' THEN 'compliance'
    WHEN type = 'security_scan' THEN 'scan'
    WHEN type = 'security_fix' THEN 'fix'
    WHEN type = 'analysis_architecture' THEN 'architecture'
    WHEN type = 'analysis_code_quality' THEN 'code_quality'
    WHEN type = 'analysis_dependencies' THEN 'dependencies'
    WHEN type = 'analysis_repo_structure' THEN 'repo_structure'
    WHEN type = 'analysis_tech_stack' THEN 'tech_stack'
    WHEN type = 'analysis_performance' THEN 'performance'
    WHEN type = 'analysis_security' THEN 'security'
    WHEN type = 'analysis_layer_violations' THEN 'layer_violations'
    WHEN type = 'optimization_performance' THEN 'performance'
    WHEN type = 'optimization_memory' THEN 'memory'
    WHEN type = 'optimization_database' THEN 'database'
    WHEN type = 'optimization_caching' THEN 'caching'
    WHEN type = 'optimization_bundling' THEN 'bundling'
    WHEN type = 'optimization_startup' THEN 'startup'
    WHEN type = 'optimization_code' THEN 'code'
    WHEN type = 'optimization_resource' THEN 'resource'
    WHEN type = 'documentation_api' THEN 'api'
    WHEN type = 'documentation_user' THEN 'user'
    WHEN type = 'documentation_technical' THEN 'technical'
    WHEN type = 'documentation_code' THEN 'code'
    WHEN type = 'documentation_guides' THEN 'guides'
    WHEN type = 'documentation_tutorials' THEN 'tutorials'
    WHEN type = 'documentation_structure' THEN 'structure'
    WHEN type = 'documentation_maintenance' THEN 'maintenance'
    WHEN type = 'generate_configs' THEN 'configs'
    WHEN type = 'generate_documentation' THEN 'documentation'
    WHEN type = 'generate_scripts' THEN 'scripts'
    WHEN type = 'generate_tests' THEN 'tests'
    WHEN type = 'generate_api_docs' THEN 'api_docs'
    WHEN type = 'generate_user_guides' THEN 'user_guides'
    WHEN type = 'management_port_streaming' THEN 'port_streaming'
    WHEN type = 'management_process_todo' THEN 'process_todo'
    WHEN type = 'management_send_message' THEN 'send_message'
    WHEN type = 'management_start_streaming' THEN 'start_streaming'
    WHEN type = 'management_stop_streaming' THEN 'stop_streaming'
    WHEN type = 'management_test_correction' THEN 'test_correction'
    WHEN type = 'management_update_test_status' THEN 'update_test_status'
    WHEN type = 'management_create_task' THEN 'create_task'
    WHEN type = 'validation_input' THEN 'input'
    WHEN type = 'validation_configuration' THEN 'configuration'
    WHEN type = 'validation_data' THEN 'data'
    WHEN type = 'validation_schema' THEN 'schema'
    WHEN type = 'validation_format' THEN 'format'
    ELSE 'general'
  END
WHERE category IS NULL OR subcategory IS NULL;

-- Add comment to document the new column
COMMENT ON COLUMN tasks.subcategory IS 'Subcategory for hierarchical task categorization'; 